# Generated by Django 6.0.7 on 2026-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_paymentid_shippingaddress_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='xendit_invoice_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
